"""Turn the JSON results in reports/ into reports/benchmark.md (run automatically by src.pipeline).

    py -3.11 -m src.make_report
"""
import json
import pickle

import numpy as np

from .paths import MODELS, REPORTS

MODEL = {"xgb": "XGBoost", "cnn": "1D CNN", "lstm": "LSTM", "transformer": "Transformer"}
POLICY = {"corrective": "Run to failure", "time_based": "Fixed interval", "predictive": "AeroTwin (predictive)", "oracle": "Perfect-RUL reference"}
PUBLISHED = {"Babu 2016 (CNN)": 18.45, "Zheng 2017 (LSTM)": 16.14, "Li 2018 (DCNN)": 12.61, "DAST 2021 (Transformer)": 11.43}
FDS = ["FD001", "FD002", "FD003", "FD004"]


def load(name):
    return json.loads((REPORTS / name).read_text())


def table(header, rows):
    return "\n".join(["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"] + ["| " + " | ".join(str(c) for c in r) + " |" for r in rows])


def main():
    out = ["# Benchmark report", "", "Generated by `src/make_report.py` from the JSON files in this folder. Do not edit by hand.", ""]

    ml = load("ml_results.json")
    by = {(r["fd"], r["model"]): r["summary"] for r in ml}
    out += ["## 1. Remaining-life prediction (NASA C-MAPSS)", "",
            "Test-set RMSE in flights (lower is better), mean over seeds, with PHM08 score in brackets. One standard pipeline, no per-subset tuning.", "",
            table(["Model", *FDS], [[MODEL[m], *[f"{by[(fd, m)]['rmse'][0]:.1f} ({by[(fd, m)]['score'][0]:.0f})" if (fd, m) in by else "-" for fd in FDS]] for m in MODEL]), "",
            "Published FD001 RMSE for reference: " + "; ".join(f"{k} {v}" for k, v in PUBLISHED.items()) + ".", ""]

    cmp_ = load("fleet_comparison.json")
    h = cmp_["headline"]
    rows = []
    for k, v in h.items():
        key = next(p for p in POLICY if k.startswith(p))
        rows.append([POLICY[key] + (f" (T={cmp_['best_T']})" if key == "time_based" else ""), f"{v['availability'][0] * 100:.1f}%", f"{v['failures'][0]:.0f}", f"{v['planned'][0]:.0f}",
                     f"{v['mean_wasted_cycles'][0]:.0f}", f"{v['cost'][0] / 1000:.1f}k"])
    out += ["## 2. Maintenance policy comparison", "",
            f"Mean over {len(cmp_['seeds'])} simulated fleets of 40 aircraft for 365 days (3 workshops, limited spare engines). The fixed interval is tuned on the same fleets it is scored on.", "",
            table(["Policy", "Availability", "Failures / yr", "Planned swaps", "Life wasted per swap (flights)", "Cost"], rows), ""]

    sens = load("fleet_sensitivity.json")
    spares = [d["spares"] for d in sens["predictive"]]
    out += ["## 3. Spare-pool sensitivity", "", "Availability against the number of spare engines (mean of 4 simulated fleets).", "",
            table(["Policy", *[f"{n} spares" for n in spares]], [[POLICY[p], *[f"{d['availability'] * 100:.1f}%" for d in sens[p]]] for p in ("predictive", "time_based", "corrective")]), ""]

    an = load("anomaly_results.json")
    out += ["## 4. Flight-data anomaly detection", "",
            f"Convolutional autoencoder trained on nominal NASA flight windows; faults injected into held-out flights. False-alarm rate on nominal test flights: {an['false_alarm_rate_nominal_test'] * 100:.1f}%.", "",
            table(["Fault", "AUROC", "AUPRC", "Recall at threshold"], [[k.replace("_", " "), f"{v['auroc']:.2f}", f"{v['auprc']:.2f}", f"{v['recall_at_thr'] * 100:.0f}%"] for k, v in an["faults"].items()]), ""]

    oof = MODELS / "ml" / "oof_FD001.pkl"
    if oof.exists():
        from .fleet.sim import SIGMA_CAL
        eng = pickle.load(open(oof, "rb"))["engines"].values()
        mu, sd = np.concatenate([e["mu"] for e in eng]), np.concatenate([e["sigma"] for e in eng])
        y = np.concatenate([np.minimum(e["true_rul"], 125) for e in eng])
        m, err = y < 100, np.abs(mu - y)
        out += ["## 5. Uncertainty calibration", "",
                f"Share of true remaining life inside the +-2 sigma interval during the wear-out phase (RUL < 100), out-of-fold: **{np.mean(err[m] <= 2 * sd[m]) * 100:.0f}%** raw, "
                f"**{np.mean(err[m] <= 2 * SIGMA_CAL * sd[m]) * 100:.0f}%** after the x{SIGMA_CAL:g} calibration used by the scheduler. The factor was chosen on this same data, so treat it as optimistic.", ""]

    nl = load("nlp_clusters.json")
    top = sorted(nl["clusters"], key=lambda c: -c["size"])[:6]
    out += ["## 6. Maintenance-log analysis", "", f"{sum(c['size'] for c in nl['clusters']):,} real aviation maintenance notes grouped into {len(nl['clusters'])} issue clusters (TF-IDF, LSA, k-means). Largest clusters:", "",
            table(["Typical words", "Part of aircraft", "Notes"], [[" / ".join(c["top_terms"][:3]), c["main_component"], c["size"]] for c in top]), ""]
    (REPORTS / "benchmark.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote reports/benchmark.md")


if __name__ == "__main__":
    main()
